### ISSUE TITLE
코딩 컨밴션

### ISSUE THREAD

**Issue by bigCoDult** [FE-6-vanilla-JS-5/vanillaJS__marketKarly#8]

**Comment by bigCoDult** [comment]
네이밍 컨밴션

언어별 패턴 분리

**Comment by bigCoDult** [comment]
html /css => 스네이크
js => 카멜

**Comment by ewsn0825** [comment]
## 코딩 컨벤션()

- 코딩 작업 시 의미 없는 class 이름을 사용하지 않는다.
- 커밋 할 때 커밋 컨벤션을 준수한다.

[[Udacity Nanodegree Style Guide](https://udacity.github.io/git-styleguide/)](https://udacity.github.io/git-styleguide/)

- 정해진 네이밍 패턴을 준수한다
    1. html /css은 스네이크 패턴을 사용한다
    2. js 에서는 카멜 케이스를 사용한다.

- 작업 중 이슈 발생 시 github issues 사용해서 이슈를 전달한다. 하기 힘들 경우에는 디코 or 카톡을 사용해 구두로 설명 후 같이 해결해본다.
    - 이슈 발생 시 스스로 해결할 수 있는 범위일 경우(구글링이나 여려 시도를 통해 해결할 수 있는 상태) ⇒ 해결 후 해결 방법 github issues 에 작성 / 해결 못 할 시엔 시도 과정과 구체적인 에러 문단을 정리하여 작성한다.
    - 이슈 발생 시 스스로 해결할 수 없는 경우(감도 안 잡히는 상태)
        1. 조원들에게 이슈를 공유하고 해결해보기
        2. 위 과정으로 해결을 못할 시 범쌤에게 물어보기 (대부분 해결 가능 할 것으로 예상)
- 가능하다면 데일리 회고를 진행하여 wiki를 작성하여 기록을 남겨본다. (사용설명서 + 회고내용으로 작성?)
- 함수형 프로그래밍을 지향하므로 함수 이름 작성 시 규칙을 정해서 작성한다. (event 실행함수 : 앞에 handler 붙이기 등)

**Comment by ewsn0825** [comment]
코딩 컨밴션 아이템
    
- 큰 따옴표 사용금지
 - 작은 따옴표 사용
 - eslint, 프리티어 이용    
    
- 무조건 세미콜론 붙여주기
 - eslint ,prettier 이용
    
- var 사용 금지
 - 가능한 const를 사용
 - let은 동적인 항목에만 사용
    
- 구현 완료시, 타이틀을 주석으로 남긴다
 - 선택사항 : 기능을 구현하는 동안 상세한 주석을 작성
    
- 함수는 가능한 최소단위로 분리 
 - 함수 네이밍 필수요소
            "has"
            "is"
            "set"
            "get…" – 값을 반환함
            "show…" - 무언가를 보여줌
            "calc…" – 무언가를 계산함
            "create…" – 무언가를 생성함
            "check…" – 무언가를 확인하고 불린값을 반환함
        항상 import와 export를 이용한다.
    
- 네이밍시, 큰 단위의 단어를 먼저 작성
 - 정렬되었을때 하위 항목을 찾기 편함
        
        X : user_data.js
        X : product_data.js
        X : card_user.js
        X : title_user.js
        
        O : data_user.js
        O : data_product.js
        O : user_card.js
        O : user_title.js
    
- 들여쓰기는 tab 방식 권장
   
- 스페이스는 연속사용 금지
    
- boolean 타입 변수 is_xxx 사용 => 접두사로 is 사용
    
- 3중 등호 연산자인 ===, !==만 사용한다.
    
- 약어보다는 길더라도 의미를 다 알수있게 적기
 - x : btn
 - o : button
    
- 객체와 배열을 생성자가 아닌 리터럴 방식으로 사용한다
 -  const arr = []
